table BaseFuncionarios
	lineageTag: 0b092bb3-30c8-48e0-936d-a4743efb357b

	column 'ID RH'
		dataType: int64
		formatString: 0
		lineageTag: da448ae4-5e12-45fa-ad19-831534974a37
		summarizeBy: sum
		sourceColumn: ID RH

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: 41f2a69e-5994-47ef-8501-e10e46ea64ad
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column 'Estado Civil'
		dataType: string
		lineageTag: 5e9a3ad7-1e90-474e-b0e6-961273a9adfe
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: cbb9f843-6445-4d1c-aabc-2cd43b218116
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column 'Data de Nascimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 549f0146-424a-44f9-b4d2-31918becd1c9
		summarizeBy: none
		sourceColumn: Data de Nascimento

		variation Variation
			isDefault
			relationship: 6b8bb0ac-e616-435c-9f8b-9f478a1cedb2
			defaultHierarchy: LocalDateTable_e6527754-6f4e-418a-b694-21d040d54664.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Endereço
		dataType: string
		lineageTag: aff0d5c8-af7e-4dc2-b38e-6362263ce73e
		summarizeBy: none
		sourceColumn: Endereço

		annotation SummarizationSetBy = Automatic

	column 'Data de Contratacao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95e3f84f-0ee3-4e17-b7f5-2f8be7a1e572
		summarizeBy: none
		sourceColumn: Data de Contratacao

		variation Variation
			isDefault
			relationship: d0dd540c-13d8-4f86-b0b8-5d9bfd108ce3
			defaultHierarchy: LocalDateTable_4a1d2719-6a45-43dd-82d9-a5aa2b4bde39.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Demissao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e73472a5-744f-45d4-92cd-0d271b00673a
		summarizeBy: none
		sourceColumn: Data de Demissao

		variation Variation
			isDefault
			relationship: 2929bb4a-f140-47db-8416-259d41b677ac
			defaultHierarchy: LocalDateTable_7b13ebdf-4ad1-4689-80c7-1add65dc301c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Salario Base'
		dataType: int64
		formatString: 0
		lineageTag: 2ad6dc3f-d323-43eb-a25c-6a92130614e4
		summarizeBy: sum
		sourceColumn: Salario Base

		annotation SummarizationSetBy = Automatic

	column Impostos
		dataType: double
		lineageTag: 1ef89196-8c67-48e0-8e37-9bc1660c1ad5
		summarizeBy: sum
		sourceColumn: Impostos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Beneficios
		dataType: double
		lineageTag: d53e8d3c-3c78-4070-9846-70bc10a690d0
		summarizeBy: sum
		sourceColumn: Beneficios

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VT
		dataType: double
		lineageTag: 463bcbde-137a-4d44-855b-306eb68b383a
		summarizeBy: sum
		sourceColumn: VT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VR
		dataType: double
		lineageTag: 0798ed3f-5460-43ec-aac3-6e3cd8f67fb5
		summarizeBy: sum
		sourceColumn: VR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cargo
		dataType: string
		lineageTag: e94321e4-173d-48cb-b009-298a54bc8158
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column Nível
		dataType: string
		lineageTag: e18396a9-ff1f-416c-9aa1-6bd2045ae376
		summarizeBy: none
		sourceColumn: Nível

		annotation SummarizationSetBy = Automatic

	column Área
		dataType: string
		lineageTag: cd569cd9-ff9d-4b7c-9142-aafe738383bd
		summarizeBy: none
		sourceColumn: Área

		annotation SummarizationSetBy = Automatic

	column 'Ferias Acumuladas'
		dataType: int64
		formatString: 0
		lineageTag: 349ea930-bab5-49b7-b960-a7806e46c482
		summarizeBy: sum
		sourceColumn: Ferias Acumuladas

		annotation SummarizationSetBy = Automatic

	column 'Horas Extras'
		dataType: int64
		formatString: 0
		lineageTag: d31310aa-f79a-4f45-b7ba-af71a35273c5
		summarizeBy: sum
		sourceColumn: Horas Extras

		annotation SummarizationSetBy = Automatic

	column Imagem
		dataType: string
		lineageTag: 474774e9-cb3e-491f-a44f-ec6a17a9f6e6
		summarizeBy: none
		sourceColumn: Imagem

		annotation SummarizationSetBy = Automatic

	column 'Avaliação do Funcionário'
		dataType: double
		lineageTag: 89f69768-0b19-41c6-bd2e-867032448f70
		summarizeBy: sum
		sourceColumn: Avaliação do Funcionário

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Trabalho em Equipe'
		dataType: int64
		formatString: 0
		lineageTag: 20b7cac2-ecad-4287-b0cb-cb0e93dd0f82
		summarizeBy: sum
		sourceColumn: Trabalho em Equipe

		annotation SummarizationSetBy = Automatic

	column Liderança
		dataType: int64
		formatString: 0
		lineageTag: a6230314-8e0f-4c9b-bc58-6f93df9e8e49
		summarizeBy: sum
		sourceColumn: Liderança

		annotation SummarizationSetBy = Automatic

	column Comunicação
		dataType: int64
		formatString: 0
		lineageTag: f2c2e686-e84b-4d09-be7e-ad48c78e3e67
		summarizeBy: sum
		sourceColumn: Comunicação

		annotation SummarizationSetBy = Automatic

	column Iniciativa
		dataType: int64
		formatString: 0
		lineageTag: 247bbdfa-012d-48da-aeb4-0ddd5c7021d8
		summarizeBy: sum
		sourceColumn: Iniciativa

		annotation SummarizationSetBy = Automatic

	column Organização
		dataType: int64
		formatString: 0
		lineageTag: 07becff7-44ae-4bcf-8b3e-0f251cbe0f2c
		summarizeBy: sum
		sourceColumn: Organização

		annotation SummarizationSetBy = Automatic

	partition BaseFuncionarios = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\flavi\Documents\GitHub\Projetos\ProjetosPowerBi\PojetosBi\Rh\AnaliseRh.xlsx"), null, true),
				    BaseFuncionarios_Table = Fonte{[Item="BaseFuncionarios",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(BaseFuncionarios_Table,{{"ID RH", Int64.Type}, {"Nome Completo", type text}, {"Estado Civil", type text}, {"Sexo", type text}, {"Data de Nascimento", type date}, {"Endereço", type text}, {"Data de Contratacao", type date}, {"Data de Demissao", type date}, {"Salario Base", Int64.Type}, {"Impostos", type number}, {"Beneficios", type number}, {"VT", type number}, {"VR", type number}, {"Cargo", type text}, {"Nível", type text}, {"Área", type text}, {"Ferias Acumuladas", Int64.Type}, {"Horas Extras", Int64.Type}, {"Imagem", type text}, {"Avaliação do Funcionário", type number}, {"Trabalho em Equipe", Int64.Type}, {"Liderança", Int64.Type}, {"Comunicação", Int64.Type}, {"Iniciativa", Int64.Type}, {"Organização", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

