table Funcionarios
	lineageTag: b40a1237-c103-4dfd-bd37-b1c79199abe3

	column 'ID RH'
		dataType: int64
		formatString: 0
		lineageTag: 33dd16fb-e93d-480f-954c-91a904f20db4
		summarizeBy: sum
		sourceColumn: ID RH

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: 296e845e-9132-4305-b366-ff846fc8cc18
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column 'Estado Civil'
		dataType: string
		lineageTag: e0bbc916-5a98-4174-9b7c-37067087da4b
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column Sexo
		dataType: string
		lineageTag: 513e9983-f27d-48f7-8cf7-15ef1d03888e
		summarizeBy: none
		sourceColumn: Sexo

		annotation SummarizationSetBy = Automatic

	column 'Data de Nascimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 77b64f8f-5997-4afe-92d3-dac747b02cdd
		summarizeBy: none
		sourceColumn: Data de Nascimento

		variation Variation
			isDefault
			relationship: f9a9c43f-80f5-4314-b229-91a4ddf67a42
			defaultHierarchy: LocalDateTable_d82d9ee3-1f03-4d3c-a3a3-75e892054d61.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Endereço
		dataType: string
		lineageTag: 4aa0efb7-4eba-4d8d-b166-95b804d04156
		summarizeBy: none
		sourceColumn: Endereço

		annotation SummarizationSetBy = Automatic

	column 'Data de Contratacao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8fa7b014-6ea8-4d13-bc9a-9f5852355d71
		summarizeBy: none
		sourceColumn: Data de Contratacao

		variation Variation
			isDefault
			relationship: 2962be26-cd66-4995-ac65-6909c47bf615
			defaultHierarchy: LocalDateTable_33e01b23-2a70-414e-9ae4-27a550f90381.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data de Demissao'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f36d2e0e-8ccc-4968-8ee0-a4afbe003da4
		summarizeBy: none
		sourceColumn: Data de Demissao

		variation Variation
			isDefault
			relationship: 08755333-7908-40ba-a430-01e5236c561b
			defaultHierarchy: LocalDateTable_c273d301-d9ea-419d-b96c-74aa8797b966.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Salario Base'
		dataType: int64
		formatString: 0
		lineageTag: d54e8250-ed98-4057-a01a-f892d3a96298
		summarizeBy: sum
		sourceColumn: Salario Base

		annotation SummarizationSetBy = Automatic

	column Impostos
		dataType: double
		lineageTag: 36706979-4bf8-41b0-b9d0-4b10eb3ad980
		summarizeBy: sum
		sourceColumn: Impostos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Beneficios
		dataType: double
		lineageTag: 2cd83745-49a1-4d90-8974-9ebc923042a4
		summarizeBy: sum
		sourceColumn: Beneficios

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VT
		dataType: double
		lineageTag: a03f8f9c-3370-4ff6-b877-15c6715ff48f
		summarizeBy: sum
		sourceColumn: VT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VR
		dataType: double
		lineageTag: 15ee0170-528b-43e0-ad13-0d4fedfb943b
		summarizeBy: sum
		sourceColumn: VR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cargo
		dataType: string
		lineageTag: 43aa4853-7c3a-4a73-9a43-456f00662483
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column Nível
		dataType: string
		lineageTag: c7985768-a964-4b69-9a2c-7d72380717e9
		summarizeBy: none
		sourceColumn: Nível

		annotation SummarizationSetBy = Automatic

	column Área
		dataType: string
		lineageTag: 3302e3bc-93d8-4c40-942e-3a2a3d44ca06
		summarizeBy: none
		sourceColumn: Área

		annotation SummarizationSetBy = Automatic

	column 'Ferias Acumuladas'
		dataType: int64
		formatString: 0
		lineageTag: e08ae360-40f2-41e6-80a2-738e1f0f90e6
		summarizeBy: sum
		sourceColumn: Ferias Acumuladas

		annotation SummarizationSetBy = Automatic

	column 'Horas Extras'
		dataType: int64
		formatString: 0
		lineageTag: 85d09b9f-2305-44c4-8b08-3eccc1d2e4bc
		summarizeBy: sum
		sourceColumn: Horas Extras

		annotation SummarizationSetBy = Automatic

	column Imagem
		dataType: string
		lineageTag: f6ee4151-6bef-4360-8da7-166b53ff15be
		summarizeBy: none
		sourceColumn: Imagem

		annotation SummarizationSetBy = Automatic

	column 'Avaliação do Funcionário'
		dataType: double
		lineageTag: 38f4dc0b-b5f6-42c9-8512-f6b387323a7b
		summarizeBy: sum
		sourceColumn: Avaliação do Funcionário

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Trabalho em Equipe'
		dataType: int64
		formatString: 0
		lineageTag: 443c9075-b330-4734-b473-b2b18d01ec38
		summarizeBy: sum
		sourceColumn: Trabalho em Equipe

		annotation SummarizationSetBy = Automatic

	column Liderança
		dataType: int64
		formatString: 0
		lineageTag: 763a9784-7ebb-4785-96cd-e7127fb0b939
		summarizeBy: sum
		sourceColumn: Liderança

		annotation SummarizationSetBy = Automatic

	column Comunicação
		dataType: int64
		formatString: 0
		lineageTag: f6511570-ab75-4340-9a8d-240103778d66
		summarizeBy: sum
		sourceColumn: Comunicação

		annotation SummarizationSetBy = Automatic

	column Iniciativa
		dataType: int64
		formatString: 0
		lineageTag: 71f010df-fc47-4922-a90d-9524a182fd42
		summarizeBy: sum
		sourceColumn: Iniciativa

		annotation SummarizationSetBy = Automatic

	column Organização
		dataType: int64
		formatString: 0
		lineageTag: 68ba5742-5de8-4abf-8d71-2f6e03dfa16c
		summarizeBy: sum
		sourceColumn: Organização

		annotation SummarizationSetBy = Automatic

	partition Funcionarios = m
		mode: import
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1-xJObKH-lTZfx67Ff8KtNz9RoONeBsqqykz8YqsLgCE/edit?usp=sharing"),
				    Folha1_Table = Fonte{[name="Folha1",ItemKind="Table"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Folha1_Table, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID RH", Int64.Type}, {"Nome Completo", type text}, {"Estado Civil", type text}, {"Sexo", type text}, {"Data de Nascimento", type date}, {"Endereço", type text}, {"Data de Contratacao", type date}, {"Data de Demissao", type date}, {"Salario Base", Int64.Type}, {"Impostos", type number}, {"Beneficios", type number}, {"VT", type number}, {"VR", type number}, {"Cargo", type text}, {"Nível", type text}, {"Área", type text}, {"Ferias Acumuladas", Int64.Type}, {"Horas Extras", Int64.Type}, {"Imagem", type text}, {"Avaliação do Funcionário", type number}, {"Trabalho em Equipe", Int64.Type}, {"Liderança", Int64.Type}, {"Comunicação", Int64.Type}, {"Iniciativa", Int64.Type}, {"Organização", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

